// scripts/achievements-booster.js
// -------------------------------------------------------------
// ⚡️ GitHub Achievements Booster
// -------------------------------------------------------------
// Automate Pull-Shark, YOLO, Galaxy Brain, etc.
// • Creates N branches
// • Modifies/creates a tiny file on each branch
// • Opens a pull-request for each branch
// • Immediately merges the PR (or waits X seconds if desired)
// -------------------------------------------------------------
// USAGE:
// 1. npm i @octokit/rest moment
// 2. export GITHUB_TOKEN="<YOUR_PAT_WITH_REPO_SCOPE>"
// 3. node scripts/achievements-booster.js owner repo \ 
//        --prs 4 --days 2 --sleep 5
// -------------------------------------------------------------
// NOTE: Running once with --days 2 (on two consecutive days) + 4 PRs/day
//       débloque Pull-Shark. Adjust parameters for other achievements.
// -------------------------------------------------------------

import { Octokit } from "@octokit/rest";
import moment from "moment";
import fs from "fs";
import path from "path";
import process from "process";
import { execSync } from "child_process";

const argv = process.argv.slice(2);
if (argv.length < 2) {
  console.error("Usage: node achievements-booster.js <owner> <repo> [--prs 4] [--days 2] [--sleep 0]");
  process.exit(1);
}

const owner = argv[0];
const repo = argv[1];

// Parse optional flags
const getFlag = (flag, def) => {
  const idx = argv.indexOf(flag);
  return idx !== -1 ? parseInt(argv[idx + 1], 10) : def;
};

const prsPerDay = getFlag("--prs", 4);
const days = getFlag("--days", 1);
const sleepSeconds = getFlag("--sleep", 0);

if (!process.env.GITHUB_TOKEN) {
  console.error("❌  Set GITHUB_TOKEN env variable with repo scope");
  process.exit(1);
}

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function getDefaultBranch() {
  const { data } = await octokit.repos.get({ owner, repo });
  return data.default_branch;
}

async function getLatestCommitSha(branch) {
  const { data } = await octokit.repos.getBranch({ owner, repo, branch });
  return data.commit.sha;
}

async function createBranch(branch, baseSha) {
  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branch}`,
    sha: baseSha,
  });
}

async function commitFile(branch, fileName, content) {
  await octokit.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: fileName,
    message: `chore: update ${fileName}`,
    content: Buffer.from(content).toString("base64"),
    branch,
  });
}

async function createAndMergePR(branch, base, title) {
  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    head: branch,
    base,
    title,
    body: "PR auto-generated by achievements-booster",
  });
  await octokit.pulls.merge({
    owner,
    repo,
    pull_number: pr.number,
    merge_method: "squash",
  });
  await octokit.git.deleteRef({ owner, repo, ref: `heads/${branch}` });
}

async function run() {
  const baseBranch = await getDefaultBranch();
  const baseSha = await getLatestCommitSha(baseBranch);

  console.log(`🚀 Target: ${owner}/${repo} (base: ${baseBranch})`);
  console.log(`⚙️  ${prsPerDay} PRs per day  •  ${days} day(s)`);

  for (let day = 0; day < days; day++) {
    const dayDate = moment().add(day, "days").format("YYYY-MM-DD");
    console.log(`\n📅 Day ${day + 1}/${days} – ${dayDate}`);

    for (let i = 0; i < prsPerDay; i++) {
      const branch = `boost/${dayDate}/pr-${i + 1}`;
      const fileName = `boost_${dayDate}_${i + 1}.txt`;
      const content = `Automated boost commit ${i + 1} on ${dayDate}\n`;

      console.log(`  ➤ Creating branch ${branch}`);
      await createBranch(branch, baseSha);

      console.log(`    • Committing ${fileName}`);
      await commitFile(branch, fileName, content);

      console.log(`    • Opening & merging PR`);
      await createAndMergePR(branch, baseBranch, `Boost commit ${i + 1} on ${dayDate}`);

      if (sleepSeconds > 0) await sleep(sleepSeconds * 1000);
    }
  }

  console.log("\n🎉  Done! Check your Achievements tab in a few minutes.");
}

run().catch((e) => {
  console.error("❌  Script failed:", e.message);
  process.exit(1);
}); 